### ISSUE TITLE
[Errno 24] Too many open files

### ISSUE THREAD

**Issue by jamespwilliams** [RIPE-NCC/ripe-atlas-cousteau#56]
I'm currently working on an academic project which uses the RIPE Atlas API heavily. Many lookups are performed, and the process performing these lookups lives for a long time (many hours).

Unfortunately, it appears that socket connections aren't getting closed by the socket.io library used by this module, which means that eventually my Python process runs out of open file descriptors. I can confirm this by running my tool and then examining the file list in `htop` - there are thousands of the form `XXX@XXX -> stream.atlas.ripe.net:80`:

```
8    IPv4                                      ***:44210->stream-tmp.ripe.net:80
    9    IPv4                                  ***:44212->stream-tmp.ripe.net:80
   10    IPv4                                  ***:44276->stream-tmp.ripe.net:80
   11    IPv4                                  ***:44278->stream-tmp.ripe.net:80
   12    IPv4                                  ***:44332->stream-tmp.ripe.net:80
   13    IPv4                                  ***:44400->stream-tmp.ripe.net:80
   14    IPv4                                  ***:44526->stream-tmp.ripe.net:80
   15    IPv4                                  ***:44446->stream-tmp.ripe.net:80
   16    IPv4                                  ***:44554->stream-tmp.ripe.net:80
   17    IPv4                                  ***:44402->stream-tmp.ripe.net:80
   18    IPv4                                  ***:44618->stream-tmp.ripe.net:80
   19    IPv4                                  ***:44650->stream-tmp.ripe.net:80
   20    IPv4                                  ***:44414->stream-tmp.ripe.net:80
   21    IPv4                                  ***:44448->stream-tmp.ripe.net:80
   22    IPv4                                  ***:44580->stream-tmp.ripe.net:80
   23    IPv4                                  ***:44652->stream-tmp.ripe.net:80
   24    IPv4                                  ***:44424->stream-tmp.ripe.net:80
   25    IPv4                                  ***:44426->stream-tmp.ripe.net:80
   26    IPv4                                  ***:44582->stream-tmp.ripe.net:80
   27    IPv4                                  ***:44608->stream-tmp.ripe.net:80
   28    IPv4                                  ***:44610->stream-tmp.ripe.net:80
   29    IPv4                                  ***:44620->stream-tmp.ripe.net:80
   31    IPv4                                  ***:44556->stream-tmp.ripe.net:80
   32    IPv4                                  ***:44416->stream-tmp.ripe.net:80
   33    IPv4                                  ***:44624->stream-tmp.ripe.net:80
   34    IPv4                                  ***:44626->stream-tmp.ripe.net:80
   35    IPv4                                  ***:44656->stream-tmp.ripe.net:80
   36    IPv4                                  ***:44658->stream-tmp.ripe.net:80
   37    IPv4                                  ***:44662->stream-tmp.ripe.net:80
   38    IPv4                                  ***:44664->stream-tmp.ripe.net:80
...
```

as I say, this goes on until my Python process runs out of open file descriptors.

The code that I'm using is along the lines of the following snippet, essentially the same as is described in the docs for this module:

```python
results = []

def on_result_response(*args):
    # append result to results array here...

channel = "atlas_result"
atlas_stream = AtlasStream()
atlas_stream.connect()
atlas_stream.bind_channel(channel, on_result_response)

(is_success, response) = atlas_request.create()

stream_parameters = {"msm": response["measurements"][0]}
atlas_stream.start_stream(stream_type="result", **stream_parameters)

logger.debug("Waiting for results")

tries = 0
while len(results) < len(probes) and tries < 20:
    atlas_stream.timeout(5)
    tries += 1

logger.debug("Got result, exiting")

atlas_stream.disconnect()

return [result for result in results if result]
```

It seems you are using https://github.com/invisibleroads/socketIO-client/, a library which hasn't been updated for many years, and has a long list of issues - including https://github.com/invisibleroads/socketIO-client/issues/147, which describes the same issue I'm having here. A more modern library exists at https://github.com/miguelgrinberg/python-socketio, it might be worth using this instead.

**Comment by jamespwilliams** [comment]
It seems making the change to use `python-socketio` wouldn't be too hard to implement. I could probably do it myself, but I'm not sure how active this repo is. Once I get a reply on this confirming that this repo is still active and accepting PRs, I might go ahead and do it.

**Comment by chrisamin** [comment]
Hey James. If you make a PR to switch this then I will take a look.

**Comment by AlfredArouna** [comment]
Hello, 
I got similar error using AtlasCreateRequest and AtlasStream to collect result. Not sure if this is related.
Here is my traceback:
```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 55, in apport_excepthook
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1245, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1285, in _fill_cache
OSError: [Errno 24] Too many open files: '/home/user/project_folder'

Original exception was:
Traceback (most recent call last):
  File "myscript.py", line 1006, in <module>
  File "myscript.py", line 715, in run_probe_measurement
  File "/home/user/.local/lib/python3.6/site-packages/ripe/atlas/cousteau/request.py", line 210, in create
  File "/home/user/.local/lib/python3.6/site-packages/ripe/atlas/cousteau/request.py", line 126, in post
  File "/home/user/.local/lib/python3.6/site-packages/ripe/atlas/cousteau/request.py", line 84, in http_method
  File "/home/user/.local/lib/python3.6/site-packages/ripe/atlas/cousteau/request.py", line 100, in get_http_method
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 119, in post
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 530, in request
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 643, in send
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 603, in urlopen
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 344, in _make_request
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 843, in _validate_conn
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 370, in connect
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/ssl_.py", line 322, in ssl_wrap_socket
  File "/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py", line 445, in load_verify_locations
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 777, in load_verify_locations
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
OpenSSL.SSL.Error: [('system library', 'fopen', 'Too many open files'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```
Line 715 in myscript.py is: 
`(is_success, response) = atlas_request.create()`

It seems more related to requests and openssl then socketIO.

**Comment by AlfredArouna** [comment]
I would like to, but the script was running on a remote server in background. It just crashed at some point and reported the error with the traceback. 
I also started to reimplement `AtlasStream` using `python-socketio`, but as you mention, API are different. Someone with the server side knowledge will be able to implement it easily.  
For now, I have this error with my implementation of `AtlasStream` using `python-socketio`:
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vagrant/.local/lib/python3.7/site-packages/socketio/client.py", line 612, in _handle_eio_message
    self._handle_connect(pkt.namespace)
  File "/home/vagrant/.local/lib/python3.7/site-packages/socketio/client.py", line 479, in _handle_connect
    self._send_packet(packet.Packet(packet.CONNECT, namespace=n))
  File "/home/vagrant/.local/lib/python3.7/site-packages/socketio/client.py", line 455, in _send_packet
    encoded_packet = pkt.encode()
  File "/home/vagrant/.local/lib/python3.7/site-packages/socketio/packet.py", line 61, in encode
    encoded_packet += self.namespace
TypeError: can only concatenate str (not "type") to str
```
I'm new using `python-socketio`, the problem seems related to Namespace.
